name: cs236860-tutorials
channels:
  - defaults
  - conda-forge
dependencies:
  - python=2.7
  - ipython
  - jupyter
  - jupyterlab
  - scipy
  - numpy=1.15
  - scikit-learn
  - opencv
  - pip:
    - matplotlib~=3.0
