name: cs236860-tutorials
channels:
  - defaults
  - conda-forge
dependencies:
  - python=2.7
  - ipython
  - jupyter
  - jupyterlab=0.35
  - scipy
  - numpy=1.15
  - scikit-learn
  - skimage
  - rise
  - pip:
    - matplotlib~=3.0
